name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Установка .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore TGBotTemplate.sln

      - name: Build
        run: dotnet build TGBotTemplate.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test TGBotTemplate.sln --no-build --configuration Release
